# Generated by Django 5.0.3 on 2024-04-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ReceitaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receita',
            name='grau_de_dificuldade',
            field=models.CharField(choices=[(' Fácil', 'Fácil'), ('Moderado', 'Moderado'), ('Difícil', 'Difícil')], max_length=16, null=True),
        ),
    ]
